name: hs_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/depth-diff-gaussian-rasterization
    - submodules/simple-knn